### ISSUE TITLE
Remove Stock for VMWs

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/CNMApp#6] opened 2018-03-30 11:36 UTC
## User Report
VMWs should not be able to see the stock

## ScreenShot
![file](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/android_screenshot922174083.jpg)
## Device Info
```
Time Stamp: 2018-03-30T11:36:23 UTC
App Version: 0.3.0 (52)
Install Source: Package Installer
Android Version: 7.0 (24)
Device Manufacturer: SAMSUNG
Device Model: SM-G930F
Display Resolution: 1920x1080
Display Density (Actual): 480dpi
Display Density (Bucket) xxhdpi
---------------------

```

**Comment by ifoche** [comment] 2018-04-02 09:06
Duplicate of #8

**Closed as completed** 2018-04-02 09:07 UTC
Labels: duplicate, invalid
